### ISSUE TITLE
Unexpected error and warnings when following installation guide.

### ISSUE THREAD

**Issue by jzamituy** [verypossible-labs/eslint-config-very#14]
## Current Behavior

When following the Getting started guide: https://github.com/verypossible-labs/eslint-config-very
Installing dependencies gives some warnings and one error:

[warning and error.txt](https://github.com/verypossible-labs/eslint-config-very/files/8941111/warning.and.error.txt)

![Untitled(1)](https://user-images.githubusercontent.com/48128628/174616442-a901d0fa-6fd5-4a0d-a790-ef6edce07b76.png)

## Expected Behavior

I expect that I can follow the installation guide without errors and warnings.
## Steps to Reproduce

Just following the guide.
### Environment

 
- Yarn version 1.22.15
- Version:
- Operating System: Ubuntu 22.04 LTS

**Comment by framerate** [comment]
Can confirm, same behavior for me with node v16.18.0 and v18.12.0

**Comment by nicolasgaviria** [comment]
@jzamituy @framerate What version of eslint are you currently using?

**Comment by framerate** [comment]
It's a fresh project, so I imagine I am using whichever version is included as a dependency. 

Or perhaps that is the fix? Maybe step one should be to install a proper version of ESlint?

**Comment by nicolasgaviria** [comment]
Can I take a look at the `dependencies` and the `devDependencies` sections of your `package.json` file?

Also, is this error appearing while executing `yarn add --dev @verypossible/eslint-config`?

**Comment by framerate** [comment]
```
▶ cat node_modules/eslint/package.json| grep version
  "version": "8.26.0",
  ```
  
  > Also, is this error appearing while executing yarn add --dev @verypossible/eslint-config?
  
  Yep, right at the beginning of the readme.
  
  Here's where I'm currently at (its a new module)
  
  ```
"dependencies": {
    "@hapi/nes": "^13.0.0",
    "jest": "^29.2.2"
  },
  "devDependencies": {
    "@types/hapi__nes": "^11.0.5",
    "@types/jest": "^29.2.0",
    "@typescript-eslint/eslint-plugin": "^5.41.0",
    "@typescript-eslint/parser": "^5.41.0",
    "@verypossible/eslint-config": "^1.6.1",
    "eslint": "^8.26.0",
    "eslint-config-prettier": "^8.5.0",
    "husky": "^8.0.1",
    "lint-staged": "^13.0.3",
    "prettier": "^2.7.1",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.4"
  },
  ```
  
  @nicolasgaviria

**Comment by framerate** [comment]
Also right now I'm trying to generated a `yarn.lock`

```
▶ yarn install
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "babel-plugin-module-resolver@>= 4.0.0".
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "eslint-import-resolver-babel-module@~5.3.1".
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "eslint-import-resolver-typescript@~2.4.0".
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "eslint-plugin-import@~2.23.4".
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "eslint-plugin-react@~7.24.0".
warning " > @verypossible/eslint-config@1.6.1" has unmet peer dependency "eslint-plugin-react-hooks@~4.2.0".
warning "@verypossible/eslint-config > eslint-import-resolver-babel-module@5.3.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
error An unexpected error occurred: "could not find a copy of eslint to link in /home/justin/code/teevee/holy-ghost/node_modules/@verypossible/eslint-config/node_modules".
```

**Comment by framerate** [comment]
Also should note, I get the same eslint error with the "manual install" option in the readme

```
▶ yarn add --dev @typescript-eslint/eslint-plugin @typescript-eslint/parser babel-plugin-module-resolver eslint eslint-config-prettier eslint-import-resolver-babel-module eslint-import-resolver-typescript eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks prettier
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @verypossible/eslint-config@1.6.1" has incorrect peer dependency "eslint-import-resolver-typescript@~2.4.0".
warning " > @verypossible/eslint-config@1.6.1" has incorrect peer dependency "eslint-plugin-import@~2.23.4".
warning " > @verypossible/eslint-config@1.6.1" has incorrect peer dependency "eslint-plugin-react@~7.24.0".
warning " > @verypossible/eslint-config@1.6.1" has incorrect peer dependency "eslint-plugin-react-hooks@~4.2.0".
warning " > eslint-import-resolver-babel-module@5.3.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
error An unexpected error occurred: "could not find a copy of eslint to link in /home/justin/code/teevee/holy-ghost/node_modules/@verypossible/eslint-config/node_modules".
info If you think this is a bug, please open a bug report with the information provided in "/home/justin/code/teevee/holy-ghost/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Comment by framerate** [comment]
@nicolasgaviria if I downgrade my eslint from v8.x to v7.x it seems to get past the error, so it would appear this library isn't compatible with eslint@8 perhaps!

**Comment by nicolasgaviria** [comment]
@framerate Thanks for the info! I'm currently working on a project which uses both eslint v8.x and this lib at the same time, with no issues. I'll take a deeper look into this and let you know as soon as I find something useful.

**Comment by framerate** [comment]
If you are using yarn, I would try pulling a fresh repository and following the directions in the readme. Seems to be 100% for me! Good luck

**Comment by nicolasgaviria** [comment]
@framerate After a quick check found a solution:

1. Uninstall the package: `yarn remove @verypossible/eslint-config`
2. Manually add the peer dependencies (specifying a version for `eslint-import-resolver-typescript`):
```bash
yarn add --dev @typescript-eslint/eslint-plugin @typescript-eslint/parser babel-plugin-module-resolver eslint eslint-config-prettier eslint-import-resolver-babel-module eslint-import-resolver-typescript@^2.5.0 eslint-plugin-import eslint-plugin-react eslint-plugin-react-hooks prettier
```
3. Install the package again: `yarn add --dev @verypossible/eslint-config`

Let me know if this solution works for you. We'll make sure to make any required updates to the lib in order to make this change definitive.

Thank you!

**Comment by jzamituy** [comment]
Closing as we are not using this package anymore, thanks guys!
